version: '3.8'

services:
  web-dev:
    build:
      context: ../../
      dockerfile: infra/docker/apps/web/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    volumes:
      # Mount source code for hot reload
      - ../../apps/web/src:/app/src
      - ../../apps/web/public:/app/public
      - ../../apps/web/next.config.ts:/app/next.config.ts
      - ../../apps/web/tailwind.config.ts:/app/tailwind.config.ts
      - ../../apps/web/tsconfig.json:/app/tsconfig.json
      - ../../apps/web/postcss.config.mjs:/app/postcss.config.mjs
      - ../../apps/web/components.json:/app/components.json
      # Exclude node_modules from volume mount
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - bidops-dev-network
    stdin_open: true
    tty: true

networks:
  bidops-dev-network:
    driver: bridge
